apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testeks15-ingress-service
  namespace: odoo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  tls:
    - hosts:
        - testeks15.ganemo.co
      secretName: testeks15-ganemo-com
  rules:
    - host: testeks15.ganemo.co
      http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: testeks15-cluster-ip-service
                port:
                  number: 8069
